from heap import Heap,MaxHeap
if __name__=='__main__':
    h=MaxHeap()
    h.insert(10)
    h.insert(20)
    h.insert(14)
    h.insert(10)
    h.insert(1)
    h.disp()
    print h.extractmax()
    h.disp()
    print h.extractmax()
    h.disp()
    print h.extractmax()
    h.disp()
    print h.extractmax()
    h.disp()
    print h.extractmax()
    h.disp()
    print h.extractmax()
    h.disp()
    print h.extractmax()
    h.disp()
    print h.extractmax()
    h.disp()
    h.insert(10)
    h.insert(20)
    h.insert(14)
    h.insert(10)
    h.insert(1)
    h.disp()
    print h.extractmax()
    h.disp()
    print h.extractmax()
    h.disp()
    print h.extractmax()
    h.disp()
    print h.extractmax()
    h.disp()
    print h.extractmax()
    h.disp()
